apiVersion: chaosblade.io/v1alpha1
kind: ChaosBlade
metadata:
  name: kill-container-process-by-id
spec:
  experiments:
  - scope: container
    target: process
    action: kill
    desc: "kill container process by id"
    matchers:
    - name: container-ids
      value:
      - "f040f331d9cbf3d9dfb268c6d5efdeff3e1060fcca4f61d652c641ed75ee5013"
    - name: process
      value: ["top"]
    - name: names
      value: ["guestbook-55645846d9-78x7w"]
    - name: namespace
      value: ["chaosblade"]